[package]
name = "snakegame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { version = "0.9", features = ["dynamic"] }
bevy = "0.9"
rand = "0.8.4"
stdext = "0.3.1"
